models/database_setup.py
from flask_sqlalchemy import SQLAlchemy


class SQLAlchemyService(object):
    def __init__(self):
        self.db = None

    def instantiate_sql_alchemy(self):
        """
            Instantiates a SQL Alchemy instance if one isn't already present
        """
        if not self.db:
            self.db = SQLAlchemy()
        return self.db

    def get_instance(self):
        """
            Getter method for the db instance
        """
        if self.db is None:
            self.instantiate_sql_alchemy()
        return self.db

    def initialize_db(self, app):
        if self.db is None:
            self.instantiate_sql_alchemy()
        self.db.init_app(app)

models/user.py
from werkzeug import generate_password_hash, check_password_hash
from models.database_setup import SQLAlchemyService

db = SQLAlchemyService().get_instance()


class User(db.Model):
    __tablename__ = 'users'

    uid = db.Column(db.Integer, primary_key=True)
    firstname = db.Column(db.String(100))
    lastname = db.Column(db.String(100))
    email = db.Column(db.String(120), unique=True)
    pwdhash = db.Column(db.String(54))

    def __init__(self, firstname, lastname, email, password):
        self.firstname = firstname.title()
        self.lastname = lastname.title()
        self.email = email.lower()
        self.set_password(password)

    def set_password(self, password):
        self.pwdhash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.pwdhash, password)

forms/address.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import SubmitField
from wtforms.validators import DataRequired


class AddressForm(FlaskForm):
    address = StringField('Address', validators=[DataRequired("Please enter an address")])
    submit = SubmitField("Search")

forms/login.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import PasswordField
from wtforms import SubmitField
from wtforms.validators import DataRequired
from wtforms.validators import Email


class LoginForm(FlaskForm):
    email = StringField(
        'Email Address',
        validators=[
            DataRequired('Please enter your email address'),
            Email('Please enter a valid email address'),
        ]
    )
    password = PasswordField('Password', validators=[DataRequired('Please enter your password')])
    submit = SubmitField('Submit')

forms/nearby.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import SubmitField
from wtforms.validators import DataRequired


class NearbySearchForm(FlaskForm):
    keyword_search = StringField('Keyword')
    address = StringField('Address', validators=[DataRequired("Please enter an address")])
    submit = SubmitField("Search")

forms/sign_up.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import PasswordField
from wtforms import SubmitField
from wtforms.validators import DataRequired
from wtforms.validators import Email
from wtforms.validators import Length


class SignUpForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired('Please enter your first name')])
    last_name = StringField('Last Name', validators=[DataRequired('Please enter your last name')])
    email = StringField(
        'Email Address',
        validators=[
            DataRequired('Please enter your email address'),
            Email('Please enter a valid email address'),
        ]
    )
    password = PasswordField(
        'Password',
        validators=[
            DataRequired('Please enter your password'),
            Length(min=6, message='Password needs to be a minimum of 6 characters'),
        ]
    )
    submit = SubmitField('Submit')

api_cmds/routes.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import session
from flask import redirect
from flask import url_for

from config import GOOGLE_NEARBY
from forms.nearby import NearbySearchForm
from logic.nearby_util import address_to_latlng
from logic.wikipedia.nearby import NearbySearchWikipedia
from logic.google_places.nearby import NearbySearchGoogle


index_page = Blueprint('index', __name__, template_folder='templates')
about_page = Blueprint('about', __name__, template_folder='templates')
home_page = Blueprint('home', __name__, template_folder='templates')


@index_page.route('/')
def index():
    return render_template('index.html')


@about_page.route('/about')
def about():
    return render_template('about.html')


@home_page.route('/home', methods=['GET', 'POST'])
def home():
    # Authorization to make sure only logged in users can see the home page
    if 'email' not in session:
        return redirect(url_for('login.login'))

    form = NearbySearchForm()

    if request.method == 'POST':
        if form.validate() is False:
            return render_template('home.html', form=form)
        else:
            address = form.address.data
            keyword_search = form.keyword_search.data

            # Use google nearby search if it is set to True in the config
            if GOOGLE_NEARBY:
                google_search = NearbySearchGoogle()
                nearby_places = google_search.find_nearby_places(keyword_search, address)

            # Else, fall back on wikipedia search
            else:
                my_coordinates = address_to_latlng(address)
                nearby_places = NearbySearchWikipedia.find_nearby_places(address, my_coordinates)

            return render_template('home.html', form=form, places=nearby_places)

    else:
        nearby_places = []
        return render_template('home.html', form=form, places=nearby_places)

templates/about.html
{% extends "layout.html" %}

{% block content %}
  <main class="about-section">
    <div class="container">

    <h2>About Learning Flask</h2>
    <p>In Learning Flask, you'll build an app that let's you find new places around you. With this app you can find places you like, and discover new points of interest wherever you are.</p>

    </div>
  </main>
{% endblock %}

templates/home.html
{% extends "layout.html" %}

{% block content %}
  <main class="hero-section">
    <div class="container">

    <br/>
    <div class="nav">
      <form method="POST" action="/home">
        {{ form.hidden_tag() }}

      <div class="form-group">
          {% if form.keyword_search.errors %}
            {% for error in form.keyword_search.errors %}
              <p class="error-message">{{ error }}</p>
            {% endfor %}
          {% endif %}

          {{ form.keyword_search(placeholder="What are you looking for?") }}

        </div>

        <div class="form-group">
          {% if form.address.errors %}
            {% for error in form.address.errors %}
              <p class="error-message">{{ error }}</p>
            {% endfor %}
          {% endif %}

          {{ form.address(placeholder="Where are you going?") }}

        </div>

        {{ form.submit(class="btn-primary") }}
      </form>
    </div>

    <div class="section-tabs">
        <div class="places">
          {% for place in places %}
            <article>
              <a class="name" href="{{ place['url'] }}" target="_blank">{{ place['name'] }}</a>
              <p> Rating: {{ place['rating'] }} </p>
                <p> Price Level: {{ place['price_level'] }} </p>
                <p> Phone: {{ place['phone'] }} </p>
            </article>
          {% endfor %}
        </div>
      </div>

      <div class="clearfix"></div>
    </div>
  </main>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block content %}
  <main class="hero-section">
    <div class="container">
      
      <div class="section-content">
        <h2>Discover places near you.</h2>
        <a href="{{ url_for('sign_up.sign_up') }}" class="btn-primary">Sign up</a> <!-- Uses blueprint tag and method name -->
        <a href="{{ url_for('about.about') }}" class="btn-secondary">Learn more</a>
      </div>

      <div class="section-device">
        <img src="static/img/device.png">
      </div>
      
      <div class="clearfix"></div>

    </div>
  </main>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600' rel='stylesheet'>
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet" >

    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" />
    <script src="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js"></script>
  </head>
  <body>
    <header>
      <div class="container">
        <h1 class="title">Find places near you.. </h1>
      </div>
    </header>
    
    {% block content %}
    {% endblock %}
    
  </body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block content %}
  <main class="container signup-section">
    <div class="section-content">
      <h2>Log in</h2>

        {% if error %}
            <p class="error-message">{{ error }}</p>
        {% endif %}

      <form method="POST" action="/login">
        {{ form.hidden_tag() }}

        <div class="form-group">
          {{ form.email.label }}

            {% if form.email.errors %}
                {% for error in form.email.errors %}
                  <p class="error-message">{{ error }}</p>
                {% endfor %}
            {% endif %}

          {{ form.email }}
        </div>

        <div class="form-group">
          {{ form.password.label }}
            {% if form.password.errors %}
                {% for error in form.password.errors %}
                  <p class="error-message">{{ error }}</p>
                {% endfor %}
            {% endif %}
          {{ form.password }}
        </div>

        {{ form.submit(class="btn-primary") }}

      </form>
    </div>
  </main>
{% endblock %}

templates/sign_up.html
{% extends "layout.html" %}

{% block content %}
  <main class="container signup-section">
    <div class="section-content">
      <h2>Create an account</h2>

      <form method="POST" action="/signup">
        {{ form.hidden_tag() }}

        <div class="form-group">
          {{ form.first_name.label }}

          {% if form.first_name.errors %}
            {% for error in form.first_name.errors %}
              <p class="error-message">{{ error }}</p>
            {% endfor %}
          {% endif %}

          {{ form.first_name }}
        </div>

        <div class="form-group">
          {{ form.last_name.label }}

          {% if form.last_name.errors %}
            {% for error in form.last_name.errors %}
              <p class="error-message">{{ error }}</p>
            {% endfor %}
          {% endif %}

          {{ form.last_name }}
        </div>

        <div class="form-group">
          {{ form.email.label }}

          {% if form.email.errors %}
            {% for error in form.email.errors %}
              <p class="error-message">{{ error }}</p>
            {% endfor %}
          {% endif %}

          {{ form.email }}
        </div>

        <div class="form-group">
          {{ form.password.label }}

          {% if form.password.errors %}
            {% for error in form.password.errors %}
              <p class="error-message">{{ error }}</p>
            {% endfor %}
          {% endif %}

          {{ form.password }}
        </div>

        {{ form.submit(class="btn-primary") }}
      </form>
    </div>
  </main>
{% endblock %}